export const MESSAGE_TYPE_TEXT = 1;
export const MESSAGE_TYPE_LOCATIONN = 2;
export const MESSAGE_TYPE_IMAGE = 3;
export const MESSAGE_TYPE_VOICE = 4;
export const MESSAGE_TYPE_FILE = 5;

export const MESSAGE_STATUS_SENDING = 1; // 信息发送中
export const MESSAGE_STAUTS_ARRIVED = 2; // 信息已送达
export const MESSAGE_STAUTS_UNARRIVED = 3; // 信息未送达

export default {
  MESSAGE_TYPE_TEXT,
  MESSAGE_TYPE_LOCATIONN,
  MESSAGE_TYPE_IMAGE,
  MESSAGE_TYPE_VOICE,
  MESSAGE_TYPE_FILE,
  MESSAGE_STATUS_SENDING,
  MESSAGE_STAUTS_ARRIVED,
  MESSAGE_STAUTS_UNARRIVED
};
