const PRIMARY = "#9C27B0";
const PRIMARY_LIGHT = "#D05CE3";
const PRIMARY_DARK = "#6a0080";
const SECDONARY = "#FBC02D";
const SECDONARY_LIGHT = "#FFF263";
const SECDONARY_DARK = "#C49000";
const TEXT_P = "#FFF";
const TEXT_S = "#000";
const WHITE = "#FFF";
const DARK = "#000";

export default {
  PRIMARY,
  PRIMARY_LIGHT,
  PRIMARY_DARK,
  SECDONARY,
  SECDONARY_LIGHT,
  SECDONARY_DARK,
  TEXT_P,
  TEXT_S,
  WHITE,
  DARK
};
