export const MAX_COMPOSER_HEIGHT = 100;
export const MIN_COMPOSER_HEIGHT = 40;
export const ACTION_BAR_HEIGHT = 40;
export const BOTTOM_ACTION_BAR_HEIGHT = 250;

export const AVATAR_HEIGHT = 40;
export const AVATAR_WIDTH = 40;
export const AVATAR_RADIUS = 20;

export const LOCATION_WIDTH = 200;
export const LOCATION_MAPVIEW_HEIGHT = 80;

export const MESSAGE_MARGIN_BOTTOM_SAME_USER = 2;
export const MESSAGE_MARGIN_BOTTOM_DEFAULT = 10;

export const DURATION_RENDER_TIME_MINUTE = 5; //最低渲染时间差

export const TEXT_SIZE_HINT = 12;
export const TEXT_SIZE_SECONDARY = 14;
export const TEXT_SIZE_PRIMARY = 16;
export const SIZE_DAY_HEIGHT = 36;
export const COMMON_PADDING = 10;
export const COMMON_INNER_PADDING = 5;
export const COMMON_MARGIN = 10;
export const COMMON_INNER_MARGIN = 5;
export const COMMON_BORDER_WIDTH = 1;
export const COMMON_BORDER_RADIUS = 4;

export default {
  COMMON_PADDING,
  COMMON_INNER_PADDING,
  COMMON_INNER_MARGIN,
  COMMON_MARGIN,
  COMMON_BORDER_WIDTH,
  COMMON_BORDER_RADIUS,
  MAX_COMPOSER_HEIGHT,
  MIN_COMPOSER_HEIGHT,
  ACTION_BAR_HEIGHT,
  BOTTOM_ACTION_BAR_HEIGHT,
  AVATAR_HEIGHT,
  AVATAR_WIDTH,
  AVATAR_RADIUS,
  LOCATION_WIDTH,
  LOCATION_MAPVIEW_HEIGHT,
  MESSAGE_MARGIN_BOTTOM_DEFAULT,
  DURATION_RENDER_TIME_MINUTE,
  TEXT_SIZE_HINT,
  TEXT_SIZE_PRIMARY
};
